agent_config:
  action_space_size: 3
  batch_size: 500
  embedding_dim: 15
  encoding_function: one_hot
  eps_decay: 100000
  eps_end: 0.1
  eps_start: 1.0
  learning_rate: 0.0001
  policy_type: DQN
  replay_capacity: 100000
hsize: 3
ndim: 6
num_episodes: 10000000
result_dir: res
update_frequency: 500
