agent_config:
  action_space_size: 3
  batch_size: 200
  embedding_dim: 200
  encoding_function: sin
  eps_decay: 15000
  eps_end: 0.05
  eps_start: 1.0
  learning_rate: 0.0001
  num_head: 1
  policy_type: ActionIn
  replay_capacity: 1000
hsize: 3
ndim: 20
num_episodes: 2000000
result_dir: res
update_frequency: 50
