agent_config:
  action_space_size: 3
  batch_size: 200
  embedding_dim: 100
  encoding_function: one_hot
  eps_decay: 15000
  eps_end: 0.05
  eps_start: 1.0
  learning_rate: 0.0001
  num_head: 1
  policy_type: DQN
  replay_capacity: 1000
hsize: 3
ndim: 6
num_episodes: 1000000
result_dir: res
update_frequency: 50
