result_dir: res
num_episodes: 5000000
ndim: 10
hsize: 3
update_frequency: 50

agent_config:
    embedding_dim: 196
    policy_type: ActionIn
    replay_capacity: 1000
    learning_rate: 1.0e-4
    batch_size: 64
    eps_start: 1.
    eps_end: 0.05
    eps_decay: 15000
    encoding_function: mnist
    num_head: 4
    num_attn: 1