result_dir: res
num_episodes: 10000000
ndim: 6
hsize: 3
update_frequency: 500

agent_config:
    embedding_dim: 15
    policy_type: DQN
    replay_capacity: 100000
    learning_rate: 1.0e-4
    batch_size: 500
    eps_start: 1.
    eps_end: 0.1
    eps_decay: 100000
    encoding_function: one_hot