result_dir: res
num_episodes: 15000000
ndim: 12
hsize: 4
update_frequency: 500

agent_config:
    embedding_dim: 50
    policy_type: DQN
    replay_capacity: 500000
    learning_rate: 1.0e-4
    batch_size: 500
    eps_start: 1.
    eps_end: 0.1
    eps_decay: 500000
    encoding_function: one_hot